### ISSUE TITLE
entry->get_text() doesn't give the actual entry text

### ISSUE THREAD

**Issue by artem-mamichev** [CSE201-project/PaperFriend-desktop-app#200]
![IMAGE 2023-01-20 01:26:17](https://user-images.githubusercontent.com/70771092/213591662-fdd44910-e4d8-44f6-8a54-74b0a8a91b4e.jpg)

**Comment by bogdanaKolic** [comment]
The analysis should now be performed on plain text, but we are keeping the html format in the entry
