### ISSUE TITLE
Find what patterns can be analyzed

### ISSUE THREAD

**Issue by Romain-Puech-BX24** [CSE201-project/PaperFriend-desktop-app#25]
Brainstorm all the kinds of patterns/correlations that could be found/tested in the data. This could include as we mentioned in yesterday's meeting:
- "Every Monday"
- "Every second Monday of the week"
- "When you do this activity"
- "When you are with person x"
etc

Next step will be to find functions to recognize them. You can create new issues for this and add the label "analysis" to them.

**Comment by artem-mamichev** [comment]
We had a meeting with the Analysis team. Our general suggestions and plan is next:

1) Every day guy open our app and chooses his values on sliders "Mood", "Sleep", "Eating healthy", "Productivity", "Communications", "Screen time" etc (values from "negative" to "positive")

2) As an input from a user we get:
[string date dd/mm/yyyy, double sliders values]

3) We analyse the mood plot and understand when it is less than avg, or have anomalies

4) Every time it happens we analyse last week and write a suggestion to a guy (e.g "try____"), where we put items which are visibly different from normal

5) We will understand which values are normal(ideal) by taking their avg for all time. 
If we have time, we can train a neural network which will give us ideal weights for every item
