### ISSUE TITLE
Create EntryCard class

### ISSUE THREAD

**Issue by Romain-Puech-BX24** [CSE201-project/PaperFriend-desktop-app#9]
Code the [EntryCard](https://github.com/CSE201-project/PaperFriend-desktop-app/wiki/EntryCard-class) class.  
Start first by using hard-coded values instead of the attributes of the associated Entry. (see the documentation for this sentence to make sense).  
When you get the above to work, you can replace these values by the ones you get from the entry attribute.  

#### Result:
An EntryCard that can be displayed on the screen

**Comment by bogdanaKolic** [comment]
Rounded corners not implemented.
Implementation only for EntryPerso.
